### ISSUE TITLE
Cannot build with create-react-app

### ISSUE THREAD

**Issue by mngu** [feathersjs/commons#68]
Hi,

I have those dependencies:
```
"@feathersjs/feathers": "^3.0.2",
"react-scripts": "1.0.14",
```
The build command failed to compile files from "commons" module because they are not in es5:
```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

        ./node_modules/@feathersjs/commons/lib/utils.js:8 

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
```

No problem with former feathersjs versions on my project.

Thanks for your help!

**Comment by daffl** [comment]
Please see the [documentation for using create-react-app](https://docs.feathersjs.com/api/client.html#create-react-app).

**Comment by dubiousdavid** [comment]
Why is this not an issue that Feathers is willing to solve? create-react-app is extremely common.
