### ISSUE TITLE
Uncaught ReferenceError: convertGetOrRemove is not defined

### ISSUE THREAD

**Issue by nmsz97** [feathersjs/commons#69]
Getting the error `Uncaught ReferenceError: convertGetOrRemove is not defined` when using Chrome WebView.

**Comment by daffl** [comment]
What transpiler and settings are you using? Is this in strict mode?

**Comment by nmsz97** [comment]
It was using a WebView on Android, seemed to work on Android 7+

**Comment by daffl** [comment]
I released a new version that should also work.
